# Generated by Django 3.0.14 on 2021-11-30 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image_dir', models.ImageField(upload_to='pharmasee/pill/%Y/%m/%d')),
                ('effect', models.CharField(max_length=500)),
                ('side_effect', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('when_to_take', models.TimeField()),
                ('taken_time', models.TimeField()),
                ('is_taken_today', models.BooleanField(default=False)),
                ('dose_taken_today', models.IntegerField(default=0)),
                ('pill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmasee.Pill')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
